sudo: false

language: node_js

node_js:
  - "4.2.1"

cache:
  directories:
    - node_modules

script: npm run ci

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
